name: Test Docker install
on:
  release:
    types: [ published ]
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_tests:


    runs-on: ubuntu-latest
    steps:
      - name: Get Repo
        uses: actions/checkout@v3
      - name : Test Docker install
        run : bash install_docker.sh
        shell : bash

