name: Test Docker install
on:
  release:
    types: [ published ]
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_tests:


    runs-on: ubuntu-latest
    steps:
      - name: Test Docker install
        uses: actions/checkout@v2
        run: bash install.sh
        shell: bash

